/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedStatusRouteImport } from './routes/_authed/status'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSandboxRouteImport } from './routes/_authed/sandbox'
import { Route as AuthedKeysRouteImport } from './routes/_authed/keys'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedChangelogRouteImport } from './routes/_authed/changelog'
import { Route as AuthedCatalogueRouteImport } from './routes/_authed/catalogue'
import { Route as AuthedAnalyticsRouteImport } from './routes/_authed/analytics'
import { Route as AuthedDocsIndexRouteImport } from './routes/_authed/docs.index'
import { Route as AuthedDocsApiIdRouteImport } from './routes/_authed/docs.$apiId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedStatusRoute = AuthedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSandboxRoute = AuthedSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKeysRoute = AuthedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChangelogRoute = AuthedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCatalogueRoute = AuthedCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyticsRoute = AuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocsIndexRoute = AuthedDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocsApiIdRoute = AuthedDocsApiIdRouteImport.update({
  id: '/docs/$apiId',
  path: '/docs/$apiId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/catalogue': typeof AuthedCatalogueRoute
  '/changelog': typeof AuthedChangelogRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/keys': typeof AuthedKeysRoute
  '/sandbox': typeof AuthedSandboxRoute
  '/settings': typeof AuthedSettingsRoute
  '/status': typeof AuthedStatusRoute
  '/docs/$apiId': typeof AuthedDocsApiIdRoute
  '/docs/': typeof AuthedDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/catalogue': typeof AuthedCatalogueRoute
  '/changelog': typeof AuthedChangelogRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/keys': typeof AuthedKeysRoute
  '/sandbox': typeof AuthedSandboxRoute
  '/settings': typeof AuthedSettingsRoute
  '/status': typeof AuthedStatusRoute
  '/docs/$apiId': typeof AuthedDocsApiIdRoute
  '/docs': typeof AuthedDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authed/analytics': typeof AuthedAnalyticsRoute
  '/_authed/catalogue': typeof AuthedCatalogueRoute
  '/_authed/changelog': typeof AuthedChangelogRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/keys': typeof AuthedKeysRoute
  '/_authed/sandbox': typeof AuthedSandboxRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/status': typeof AuthedStatusRoute
  '/_authed/docs/$apiId': typeof AuthedDocsApiIdRoute
  '/_authed/docs/': typeof AuthedDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/analytics'
    | '/catalogue'
    | '/changelog'
    | '/dashboard'
    | '/keys'
    | '/sandbox'
    | '/settings'
    | '/status'
    | '/docs/$apiId'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/analytics'
    | '/catalogue'
    | '/changelog'
    | '/dashboard'
    | '/keys'
    | '/sandbox'
    | '/settings'
    | '/status'
    | '/docs/$apiId'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authed/analytics'
    | '/_authed/catalogue'
    | '/_authed/changelog'
    | '/_authed/dashboard'
    | '/_authed/keys'
    | '/_authed/sandbox'
    | '/_authed/settings'
    | '/_authed/status'
    | '/_authed/docs/$apiId'
    | '/_authed/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/status': {
      id: '/_authed/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthedStatusRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sandbox': {
      id: '/_authed/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof AuthedSandboxRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/keys': {
      id: '/_authed/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthedKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/changelog': {
      id: '/_authed/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthedChangelogRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/catalogue': {
      id: '/_authed/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AuthedCatalogueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics': {
      id: '/_authed/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthedAnalyticsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/docs/': {
      id: '/_authed/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof AuthedDocsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/docs/$apiId': {
      id: '/_authed/docs/$apiId'
      path: '/docs/$apiId'
      fullPath: '/docs/$apiId'
      preLoaderRoute: typeof AuthedDocsApiIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAnalyticsRoute: typeof AuthedAnalyticsRoute
  AuthedCatalogueRoute: typeof AuthedCatalogueRoute
  AuthedChangelogRoute: typeof AuthedChangelogRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedKeysRoute: typeof AuthedKeysRoute
  AuthedSandboxRoute: typeof AuthedSandboxRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedStatusRoute: typeof AuthedStatusRoute
  AuthedDocsApiIdRoute: typeof AuthedDocsApiIdRoute
  AuthedDocsIndexRoute: typeof AuthedDocsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAnalyticsRoute: AuthedAnalyticsRoute,
  AuthedCatalogueRoute: AuthedCatalogueRoute,
  AuthedChangelogRoute: AuthedChangelogRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedKeysRoute: AuthedKeysRoute,
  AuthedSandboxRoute: AuthedSandboxRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedStatusRoute: AuthedStatusRoute,
  AuthedDocsApiIdRoute: AuthedDocsApiIdRoute,
  AuthedDocsIndexRoute: AuthedDocsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
